project_id = "oizymmjlgmwiuevksxos"

[functions.setup-first-admin]
verify_jwt = false

[functions.verificar-status-eventos]
verify_jwt = false

[functions.buscar-cliente-por-documento]
verify_jwt = false
